### ISSUE TITLE
Can't start GetProductUpdatesFromAmazonBot.py

### ISSUE THREAD

**Issue by giuseppe99barchetta** [dhirajshrotri/GetUpdatesFromAmazonBot#1]
Hi! How are you?

I'm trying to use your script but when I start it some errors shown:

`Traceback (most recent call last):
  File ".\GetProductUpdatesFromAmazonBot.py", line 44, in <module>
    main()
  File ".\GetProductUpdatesFromAmazonBot.py", line 34, in main
    all_updates = dhirajBot.getUpdates(new_offset)
  File ".\GetProductUpdatesFromAmazonBot.py", line 18, in getUpdates
    result_json = resp.json()['result']
KeyError: 'result'`

Can you explain me more?

**Comment by dhirajshrotri** [comment]
Hi @giuseppe99barchetta, you are getting a `KeyError` which means that you are trying to access a key which is not present in the dict (in this case `resp` that we get as response to the api-call on line 22). Can you print the response from the api and check if the api is returning an appropriate response?
